print('VSCode is awesome!')
print('I love coding in VSCode.')
print('This is a test for VSCode integration.')
print('Adding another line to test git functionality.')
print('This is testing my command line skills.')